### ISSUE TITLE
upgrade from beta to 1.x?

### ISSUE THREAD

**Issue by razvan-ig** [nutanix/helm#12]
Hi - when upgrading a running cluster from `ntnx/ntnx-csi:beta2` (released end 2018) to `ntnx/ntnx-csi:v1.1.1` deployed using the current chart, the StorageClass (named acs-abs at the time) cannot be kept, as the `csi-provisioner-ntnx-plugin-0` pod gets stuck in a crash loop; setting up with a different name (nutanix-volume by default) does work, but the old volumes are now orphaned. Is there a workaround to import the existing volumes into the new driver?

**Comment by tuxtof** [comment]
Hi Raz

yes there is parameters change between ntnx/ntnx-csi:beta2 StorageClass and the one from ntnx/ntnx-csi:v1.1.1

the correct upgrade procedure is to recreate a new StorageClass changing only invalid parameters and keeping the same StorageClass name

++
