### ISSUE TITLE
Use existing secret / disable secret generation

### ISSUE THREAD

**Issue by naibaf0** [nutanix/helm#30]
Hello,

would it be possible to add something like an "existingSecret" field to the values file?

We apply secrets manually to the cluster, to keep the User/Password information outside of our pipelines/code-repos, so if there was a possibility to just specify the name of a secret (or that a secret of the name `ntnx-secret` doesn't need to be created) to avoid creating or editing the secret through the helm chart, that would be great.

**Comment by tuxtof** [comment]
Hello @naibaf0 

ok i will add it in the next version , very soon

**Comment by tuxtof** [comment]
fix in #31 

just set `createSecret` value to `false`
and it will use the `secretName` value as secret

**Comment by naibaf0** [comment]
Thank you!
