### ISSUE TITLE
Possible to upgrade metrics-server from `0.3.7` to `0.6.0`

### ISSUE THREAD

**Issue by omBratteng** [nutanix/helm#46]
Hello,

Would it be possible to update the chart for metrics-server, so that the version of metrics-server is `v0.6.0`?

There has been some performance improvements of metrics-server since `v0.3.7`.

**Comment by tuxtof** [comment]
Hi @omBratteng 
i'm thinking to remove the metrics-server chart from here because it is nothing more than the original one with a default a different values settings.

Your view ?

**Comment by omBratteng** [comment]
I don't mind using the original chart, prefer that actually. But it would be nice the know which of the settings has been changed, and why (if they're required in Karbon)

**Comment by tuxtof** [comment]
Hello @omBratteng 

ok so from the original chart

helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
helm install -n kube-system metrics-server metrics-server/metrics-server --set "args={--kubelet-insecure-tls}"

as you see for the moment we need to use the --kubelet-insecure-tls args as stated in the official metrics server docs here 
https://github.com/kubernetes-sigs/metrics-server#requirements

actually  in karbon 2.3 Kubelet certificate is not signed by cluster Certificate Authority
it will be fixed soon in a coming version

another alternative is to use prometheus-adapter in place of metrics-server as prometheus is built-in in Karbon.

you can follow the documentation here

https://www.nutanix.dev/2021/11/17/karbon-and-metrics-api-a-practical-guide/

**Comment by omBratteng** [comment]
Sweet, thanks.
I was wondering why the `--kubelet-insecure-tls` was set, but thanks for clarifying it.

Any hint of when next version of karbon is released (weeks? months?)
I've seen [CNCF conformance testing](https://github.com/cncf/k8s-conformance/pull/1763) for karbon 2.4

**Comment by tuxtof** [comment]
yes 2.4 will be there in few weeks if all the last tests stay green :-D

stay tuned

**Comment by tuxtof** [comment]
Hello @omBratteng 

Karbon 2.4 is out
i let you check the following article

https://www.nutanix.dev/2022/02/17/karbon-and-metrics-api-lighter-approach-with-metrics-server/

Take care

**Comment by omBratteng** [comment]
So with karbon 2.4, `--kubelet-insecure-tls` is no longer needed?

**Comment by tuxtof** [comment]
exactly
