### ISSUE TITLE
Default to reclaimPolicy: Delete ?

### ISSUE THREAD

**Issue by vfrans** [nutanix/helm#49]
Hi!

Looking through the helm chart, it seems like the default is to set the reclaimPolicy to Delete and not have a way to set it to Retain.

Is it something that is wanted or do you accept PR to have that switch implemented?

**Comment by tuxtof** [comment]
good idea , you PR are welcome

**Comment by tuxtof** [comment]
Hello @vfrans 
v2.5.2 was released with #50
