### ISSUE TITLE
NTNX case 00575424 : use correct version numbers

### ISSUE THREAD

**Issue by virtrixke** [nutanix/helm#5]
There is an issue with the current chart. Please modify the images to v1.0.1. Some images in the values.yaml file are 1.0.2 and some are 1.0.0 causing intermittent VG discovery and mount issues:

```
#csi-image

attacherImageFinal: quay.io/k8scsi/csi-attacher:v1.0.1
attacherImageBeta: quay.io/k8scsi/csi-attacher:v0.4.2

nodeImageFinal: quay.io/k8scsi/csi-node-driver-registrar:v1.0.1
nodeImageBeta: quay.io/k8scsi/driver-registrar:v0.4.2

provisionerImageFinal: quay.io/k8scsi/csi-provisioner:v1.0.1
provisionerImageBeta: quay.io/k8scsi/csi-provisioner:v0.4.2

#csi-ntnx

ntnxImageFinal: ntnx/ntnx-csi:v1.0.1
ntnxImageBeta: ntnx/ntnx-csi:beta2
```

**Comment by tuxtof** [comment]
Hello Vincent, there is no relation between ntnx/ntnx-csi version and quay.io/k8scsi/csi-* version
There is different lifecyle

ntnx/ntnx-csi is developed by Nutanix based on the CSI framework and you are right the last version is 1.0.1 so we need to update the helm chart to reflect the change

concerning the other csi-* container they are all part of the csi framework and have each different version , we need to check the release notes of the more recent version and test the behaviour with our own component

update is coming soon
stay tuned

**Comment by tuxtof** [comment]
Vincent, i create a new chart with our ntnx/ntnx-csi:v1.0.1
other component don't need update for now

Enjoy
