### ISSUE TITLE
Read me documentation for deploying csi needs to be clear about prismEndpoint parameter

### ISSUE THREAD

**Issue by chandru-tkc** [nutanix/helm#55]
Coming from a support case logged recently, while deploying chart  with following command 

helm install nutanix-storage nutanix/nutanix-csi-storage -n ntnx-system --create-namespace --set volumeClass=true --set prismEndPoint=X.X.X.X --set username=admin --set password=xxxxxxxxx --set storageContainer=container_name --set fsType=xfs

there is a confusion with the prismEndpoint parameter, users are mistakenly setting it to Prism Central IP address which causes failure in creating PVC. Need a note explaining this should be the Prism Element cluster Virtual IP address where the k8s vms are running,

**Comment by tuxtof** [comment]
I agree let's fix the example
