### ISSUE TITLE
Install without Internet.

### ISSUE THREAD

**Issue by centrair-hoya** [nutanix/helm#71]
Hello, Nutanixers.

We are planning upgrade CSI Driver from 2.3 to latest.
Clusters are running in dark site, We cannot get helm charts from internet.

How pulll CSI images from repository?

**Comment by tuxtof** [comment]
Hello @centrair-hoya 

classic helm/airgap procedure

identify all needed images from the helm value file
push them in your own private repo
next modify corresponding helm value file to point to your repo before installing it
