### ISSUE TITLE
Feature request: Publish CSI driver also for Docker Swarm

### ISSUE THREAD

**Issue by olljanat** [nutanix/helm#92]
This would be more like [nutanix/csi-plugin](https://github.com/nutanix/csi-plugin) issue but as it read-only I write it here.

Recently published Docker 23.0.0 added CSI support for Swarm mode so it should be possible to make Nutanix CSI plugin working with Docker Swarm now.

I have build some example scripts and guidance to https://github.com/olljanat/csi-plugins-for-docker-swarm which you might find useful.

**Comment by tuxtof** [comment]
Hi @olljanat 

no problem to ask the question here.

For the moment there is no short term plan to support swarm but as long as Docker Swarm implements the CSI specification correctly I see no reason the driver couldn't be used with it.
 
Did you already test it ?
