### ISSUE TITLE
Source code of Nutanix plugin

### ISSUE THREAD

**Issue by fjcloud** [nutanix/helm#95]
Hello, 

This repo doesn't replace https://github.com/nutanix/csi-plugin , where is source code of csi-plugin ? It is no longer Open Source ?

Regards,

Florian

**Comment by vnephologist** [comment]
Hi Florian - the CSI driver is not open source, but we do have plans to open source with a new major version that is our roadmap. Stay tuned!

**Comment by olljanat** [comment]
@tuxtof I see that this was closed as completed so where are CSI plugin source codes?
